### ISSUE TITLE
Dispellable Enrage effects not working.

### ISSUE THREAD

**Issue by arcadepro** [Adirelle/LibPlayerSpells-1.0#77]
Hunter Tranq Shot not highlighted when a mob has an Enrage effect that can be dispelled.

**Comment by Rainrider** [comment]
Where did you test this? Could it be that it was with a buff LibDispellable does not know about? LD needs a list of enrage spell ids as it doesn't trust the 9th return of UnitAura because of some API limitations.

I found a nice spot to test it in Townlong Steppes (at 18, 57). The Kunchongs there have an enrage ability called Unstable Strength (91668), which was not in LibDispellable. After adding it, it all worked.

fetchEnrageList.sh needs to be run anew.

**Comment by Rainrider** [comment]
Follow-up: re-running fetchEnrageList.sh as is won't add the missing enrage ids, because http://www.wowdb.com/spells?filter-dispel-type=9 returns paged results (100 per page), so the script will get only the first 100.

**Comment by arcadepro** [comment]
Oh LibDispellable is to blame. Might as well close this issue here.

**Comment by Adirelle** [comment]
I updated fetchEnrageList.sh to scan the paged results and LibDispellable to include them.
